logging:
  level:
    root: info
    #org.springframework.jdbc: debug
##Spring Datasource
spring.datasource:
  username: ENC(4PD683gP+MUwg+gkEJLPXQ==)
  password: ENC(FhsScCfMiLX7MMpScGciKw==)
  url: jdbc:oracle:thin:@10.201.5.153:49161:XE
  driver-class-name: oracle.jdbc.OracleDriver
  #initialization-mode: always
  initialization-mode: never
  platform: oracle

spring.batch:
    jdbc:
      #initialize-schema: always
      initialize-schema: never
mybatis:
  type-aliases-package: com.example.batchdemo.dto
  mapper-locations: /mapper/**/*.xml
  executor-type: BATCH
  configuration:
    map-underscore-to-camel-case: true
    vfsImpl: org.mybatis.spring.boot.autoconfigure.SpringBootVFS

openapi:
  data.go.kr:
    key: ENC(rRhgbPILwZP3bxnkYP5xegHH3XmJCxuEtk3aqD/N1a6I9BhQhysejl5W2lE8PE+EPAbbuRwWHY/zr6bst8gvjnCVCswEIgRul6/B3ZMq88MAR40F08FRCveSWRSXJTpyeGnEh7h7Vl0=)
    hospital:
      url: http://apis.data.go.kr/B552657/HsptlAsembySearchService/getHsptlMdcncListInfoInqire

---
####################################################################################################
## test 전용 환경
####################################################################################################
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle;
    username: testdb
    password: testdb
    initialization-mode: always
    schema: classpath:test-schema-h2.sql
    #data: classpath:test-data-h2.sql
  batch:
    jdbc:
      initialize-schema: always
      platform: h2